### ISSUE TITLE
[BUG/ISSUE] Fail in regriding restart file using gcpy

### ISSUE THREAD

**Issue by Alex-Fang66** [geoschem/gchp#215]
### What institution are you from?
NUIST

### Description of the problem
Hi, I am a new user to GCHP.
My python command is : "
         python -m gcpy.file_regrid                           \
     -i initial_GEOSChem_rst.c48_fullchem.nc          \
     --dim_format_in checkpoint                             \
     --dim_format_out checkpoint                          \
     --cs_res_out 48                                                \
     --sg_params_out 2.0 103.0 36.8                      \
     -o initial_GEOSChem_rst.c48_2_103_fullchem.nc "
I firstly used GCPY with a python version of 3.9.6  when trying to do a  Stretched-Grid Simulation. I will attach the bug log(regrid.log). It seems that the GCPY cannot concat dim and generate six initial ncfiles and a bulk of conservative*nc files.![python3 9](https://user-images.githubusercontent.com/65645232/163956073-52a130af-9e91-44f0-a974-9791bb7cdf69.png)
[regrid.log](https://github.com/geoschem/GCHP/files/8511117/regrid.log)

So I tried GCPY with a python version of 3.8.8, it generated a full initial ncfile and a bulk of conservative*nc files. However, the GCHP corrupted each time when initializing grid with the initial ncfile. And I found there may be some problems with info about LON in the initial ncfile. I will attach the python log (regird2.log) and ncdump log of the initial ncfile here(stretched.log).
[stretched.log](https://github.com/geoschem/GCHP/files/8511222/stretched.log)
[regrid2.log](https://github.com/geoschem/GCHP/files/8511223/regrid2.log)

If there is no problems with the initial*nc file, please see the runConfig.rc and the crashed log.
[runConfig.txt](https://github.com/geoschem/GCHP/files/8511375/runConfig.txt)
[gchp.log.txt](https://github.com/geoschem/GCHP/files/8511376/gchp.log.txt)

Best wishes!

### GEOS-Chem version
Enter your GEOS-Chem version here.
GCHP13.3.3.4

### Software versions
- Compilers (Intel or GNU, and version):
- gcc-9.3.0
- NetCDF version: 4.5.3
- MPI version: openmpi-4.0.4
- ESMF version: 8.0.1

**Comment by LiamBindle** [comment]
Hi @Alex-Fang66,

Thanks for writing. It looks like the new version of xarray (which is being used in your Python 3.9 stack) uses some different arguments to combine those conservative*nc files. I will have to update that. The output should be identical with the 3.8 or 3.9 however. 

In `runConfig.sh` you accidentally have 
```
TARGET_LAT=103.0
TARGET_LON=36.8
```
Swapping these two should fix the issue. Can you let me know if you still have issues?

**Comment by LiamBindle** [comment]
For the gcpy bug related to the python 3.9 stack, I opened this: https://github.com/geoschem/gcpy/issues/148.

**Comment by Alex-Fang66** [comment]
Thanks for help @LiamBindle . The stretched grid simulation works fine now. I still have a question about the regrid label in HISTORY.rc, it's fabulous to convert the output into lonlat directly, but we can choose higher resolution lonlat compared what we run without raise any error message. Is this because some interpolation is carried out directly, and is the output reliable?

**Comment by sdeastham** [comment]
For the output in HISTORY you can choose either bilinear interpolation (default) or conservative regridding. In both cases you do of course "lose" some information since almost any regridding operation introduces loss, but there shouldn't be anything unreliable about either approach. If you prefer not to work with the cubed sphere output directly (understandable!) then I'd say it's actually better to work with a higher-resolution lat-lon output, as this reduces the "diffusion" of the output at the expense of introducing redundant data and increasing output file size.

**Comment by Alex-Fang66** [comment]
Thanks @sdeastham , I get it.
